/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DanielRouteImport } from './routes/daniel'
import { Route as KingsRouteImport } from './routes/kings'
import { Route as MapRouteImport } from './routes/map'
import { Route as ParablesRouteImport } from './routes/parables'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DanielRoute = DanielRouteImport.update({
  id: '/daniel',
  path: '/daniel',
  getParentRoute: () => rootRouteImport,
} as any)
const KingsRoute = KingsRouteImport.update({
  id: '/kings',
  path: '/kings',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ParablesRoute = ParablesRouteImport.update({
  id: '/parables',
  path: '/parables',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daniel': typeof DanielRoute
  '/kings': typeof KingsRoute
  '/map': typeof MapRoute
  '/parables': typeof ParablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daniel': typeof DanielRoute
  '/kings': typeof KingsRoute
  '/map': typeof MapRoute
  '/parables': typeof ParablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daniel': typeof DanielRoute
  '/kings': typeof KingsRoute
  '/map': typeof MapRoute
  '/parables': typeof ParablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/daniel' | '/kings' | '/map' | '/parables'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daniel' | '/kings' | '/map' | '/parables'
  id: '__root__' | '/' | '/daniel' | '/kings' | '/map' | '/parables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DanielRoute: typeof DanielRoute
  KingsRoute: typeof KingsRoute
  MapRoute: typeof MapRoute
  ParablesRoute: typeof ParablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daniel': {
      id: '/daniel'
      path: '/daniel'
      fullPath: '/daniel'
      preLoaderRoute: typeof DanielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kings': {
      id: '/kings'
      path: '/kings'
      fullPath: '/kings'
      preLoaderRoute: typeof KingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parables': {
      id: '/parables'
      path: '/parables'
      fullPath: '/parables'
      preLoaderRoute: typeof ParablesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DanielRoute: DanielRoute,
  KingsRoute: KingsRoute,
  MapRoute: MapRoute,
  ParablesRoute: ParablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
